package com.elroi.lemurloop.service

/**
 * Central source of truth for intent extra keys used by alarm-related components.
 *
 * Kept Android-free so it can be referenced safely from JVM unit tests.
 */
object AlarmIntentExtras {

    const val EXTRA_ALARM_ID = "ALARM_ID"
    const val EXTRA_ALARM_LABEL = "ALARM_LABEL"
    const val EXTRA_MATH_DIFFICULTY = "ALARM_MATH_DIFFICULTY"
    const val EXTRA_MATH_PROBLEM_COUNT = "ALARM_MATH_PROBLEM_COUNT"
    const val EXTRA_MATH_GRADUAL_DIFFICULTY = "ALARM_MATH_GRADUAL_DIFFICULTY"
    const val EXTRA_SNOOZE_DURATION = "ALARM_SNOOZE_DURATION"
    const val EXTRA_SNOOZE_COUNT = "ALARM_SNOOZE_COUNT"
    const val EXTRA_SMILE_TO_DISMISS = "ALARM_SMILE_TO_DISMISS"
    const val EXTRA_SMILE_FALLBACK_METHOD = "ALARM_SMILE_FALLBACK_METHOD"
    const val EXTRA_BRIEFING_ENABLED = "ALARM_BRIEFING_ENABLED"
    const val EXTRA_TTS_ENABLED = "ALARM_TTS_ENABLED"
    const val EXTRA_IS_EVASIVE_SNOOZE = "ALARM_IS_EVASIVE_SNOOZE"
    const val EXTRA_EVASIVE_SNOOZES_BEFORE_MOVING = "ALARM_EVASIVE_SNOOZES_BEFORE_MOVING"
    const val EXTRA_BRIEFING_TEXT = "EXTRA_BRIEFING_TEXT"
    const val EXTRA_SOUND_URI = "ALARM_SOUND_URI"
    const val EXTRA_IS_SMOOTH_FADE_OUT = "ALARM_IS_SMOOTH_FADE_OUT"
    const val EXTRA_IS_VIBRATE = "ALARM_IS_VIBRATE"
    const val EXTRA_IS_SOUND_ENABLED = "ALARM_IS_SOUND_ENABLED"
    const val EXTRA_IS_SNOOZE_ENABLED = "ALARM_IS_SNOOZE_ENABLED"
    const val EXTRA_IS_SMART_WAKEUP_ENABLED = "ALARM_IS_SMART_WAKEUP_ENABLED"
    const val EXTRA_WAKEUP_CHECK_DELAY = "ALARM_WAKEUP_CHECK_DELAY"
    const val EXTRA_WAKEUP_CHECK_TIMEOUT = "ALARM_WAKEUP_CHECK_TIMEOUT"
    const val EXTRA_DAYS_OF_WEEK = "ALARM_DAYS_OF_WEEK"
    const val EXTRA_BRIEFING_TIMEOUT = "ALARM_BRIEFING_TIMEOUT"
    const val EXTRA_VIBRATION_PATTERN = "ALARM_VIBRATION_PATTERN"
    const val EXTRA_VIBRATION_START_GAP = "ALARM_VIBRATION_START_GAP"
}

